[package]
name = "pdftext"
version = "0.1.1"
authors = ["Will Page <compenguy@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
pdf = { git = "https://github.com/pdf-rs/pdf", version = "0.7.2" }

